# Generated by Django 2.1 on 2019-05-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserLogin',
        ),
    ]
